<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Shared.props" />
  <PropertyGroup>
    <RootNamespace>Coworkee.Infrastructure</RootNamespace>
    <AssemblyName>Coworkee.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\lib\Coworkee.Infrastructure\Coworkee.Infrastructure.csproj" />
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
</Project>