<Project Sdk="Microsoft.NET.Sdk.Web">
  <Import Project="..\..\Shared.props" />
  <PropertyGroup>
    <RootNamespace>Coworkee.Server</RootNamespace>
    <AssemblyName>Coworkee.Server</AssemblyName>
  </PropertyGroup>
  <PropertyGroup>
    <DocumentationFile>Coworkee.Server.xml</DocumentationFile>
    <NoWarn>1701;1702;1591</NoWarn>
    <UserSecretsId>aa8b7360-671b-4ab2-99b0-7df28629ef3d</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>
  <ItemGroup>
    <Content Include=".config\dotnet-tools.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Microsoft.Azure.SignalR" Version="1.29.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="Nextended.Imaging" Version="9.0.0" />
    <PackageReference Include="Hangfire" Version="1.8.17" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.8.17" />
    <PackageReference Include="LazyCache.AspNetCore" Version="2.4.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Aspire.Keycloak.Authentication" Version="9.0.0-preview.5.24551.3" />
    <PackageReference Include="Mime" Version="3.6.0" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="NSwag.AspNetCore" Version="14.2.0" />
    <PackageReference Include="NSwag.MSBuild" Version="14.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="$(MicrosoftPackagesVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Grpc.AspNetCore" Version="2.67.0" />
    <PackageReference Include="Grpc.AspNetCore.Web" Version="2.67.0" />
    <PackageReference Include="SkiaSharp" Version="3.116.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.116.1" />
    <PackageReference Include="Svg.Skia" Version="2.0.0.4" />
    <Protobuf Include=".\gRPC\Main.proto" GrpcServices="Server" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="9.1.1" />
    <PackageReference Include="TranslatorService" Version="3.0.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Condition="'$(HostClientInServer)' == 'true'" Include="..\Client\Client.csproj" />
    <ProjectReference Include="..\Aspire\Coworkee.ServiceDefaults\Coworkee.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="nksoft.MakeGenericAgain" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Condition="'$(HostClientInServer)' == 'true'" Remove="wwwroot\index.html" />
    <Content Condition="'$(HostClientInServer)' == 'true'" Remove="wwwroot\index.html" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\swagger-ui\scripts.js" />
  </ItemGroup>

  <Target Name="NSwag" AfterTargets="Build" Condition="'$(Configuration)' == 'Debug'">
    <Copy SourceFiles="@(Reference)" DestinationFolder="$(OutDir)References" />
    <Exec Command="$(NSwagExe_Net90) run /v1/swagger.json /variables:Configuration=$(Configuration)" />
    <RemoveDir Directories="$(OutDir)References" />
  </Target>


  <Target Name="MakeGenericAgain" AfterTargets="NSwag" Condition="'$(Configuration)' == 'Debug'">
    <Exec IgnoreExitCode="true" Command="dotnet tool install --global makeGenericAgain" />
    <!--<Exec Command="makeGenericAgain -f $(SolutionDir)src/SDK/Net/v1/ClientGenerated.cs" />-->
    <Exec Command="makeGenericAgain -f &quot;$(MSBuildProjectDirectory)\..\SDK\Net\v1\ClientGenerated.cs&quot;" />
  </Target>

</Project>