version: '3.4'

services:
  Coworkee:
    image: ${DOCKER_REGISTRY-}coworkee
    build:
      context: .
      dockerfile: src/Server/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=db;Database=Coworkee;User=sa;Password=Your_password123;MultipleActiveResultSets=true;TrustServerCertificate=true"
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80;https://+:443"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=securePassword123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
      - ~/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
      - ./src/Server/Files:/app/Files
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db
    restart: on-failure
    container_name: coworkee

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Your_password123"
      - "ACCEPT_EULA=Y"
    container_name: mssql