<Project>
  <PropertyGroup>
    <HostClientInServer>true</HostClientInServer>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable> <!-- TODO: disable nullable for now because it breaks db operations but we want to enable it  -->
    <MicrosoftPackagesVersion>10.0.0</MicrosoftPackagesVersion>
    <NextendedVersion>10.0.0</NextendedVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(HostClientInServer)' == 'true'">
    <DefineConstants>HostClient</DefineConstants>
  </PropertyGroup>
</Project>
