<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Shared.props" />
  <PropertyGroup>
    <RootNamespace>Coworkee.Domain</RootNamespace>
    <AssemblyName>Coworkee.Domain</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
</Project>