<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <RootNamespace>Coworkee.Domain</RootNamespace>
    <AssemblyName>Coworkee.Domain</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Entities\Identity\" />
    <Folder Include="Entities\Notifications\" />
  </ItemGroup>
</Project>