<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\MyApp.Contracts\MyApp.Contracts.csproj" />
    <CoworkeePackage Include="Coworkee.AspNetCore" />
    <CoworkeePackage Include="Coworkee.Infrastructure" />
    <CoworkeePackage Include="Coworkee.Storage" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
</Project>
