<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Coworkee.SDK</RootNamespace>
    <AssemblyName>Coworkee.SDK</AssemblyName>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <PropertyGroup>
    <Title>Coworkee.SDK</Title>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageId>Coworkee.SDK</PackageId>
    <PackageVersion>0.0.0-dev</PackageVersion>
    <Authors>fgilde</Authors>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryType>Git</RepositoryType>
    <PackageProjectUrl>https://github.com/fgilde/Nextended</PackageProjectUrl>
    <RepositoryUrl>https://github.com/fgilde/Nextended</RepositoryUrl>
    <Description>
      Provides a SDK for using API of Coworkee
    </Description>
    <Copyright>Copyright © $(Authors) 2020-$([System.DateTime]::Now.Year)</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>SDK,HTTP,Client,Coworkee</PackageTags>
    <!--<PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>-->
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj">
      <CopyLocal>
      </CopyLocal>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Net\Extensions\" />
  </ItemGroup>
  <Target Name="CopyPackage" AfterTargets="Build">
    <ItemGroup>
      <SdkPackageFiles Include="$(ProjectDir)bin/$(Configuration)/*.nupkg" />
    </ItemGroup>
    <Copy SourceFiles="@(SdkPackageFiles)" DestinationFolder="$(MSBuildProjectDirectory)\..\Server\wwwroot\sdk" />
  </Target>
</Project>