<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>CleanArchitectureBase.Shared</RootNamespace>
    <AssemblyName>CleanArchitectureBase.Shared</AssemblyName>
  </PropertyGroup>

  
  <ItemGroup>
    <EmbeddedResource Include="Resources\ar-SA.yml" />
    <EmbeddedResource Include="Resources\bg-BG.yml" />
    <EmbeddedResource Include="Resources\de-DE.yml" />
    <EmbeddedResource Include="Resources\en-US.yml" />
    <EmbeddedResource Include="Resources\es-ES.yml" />
    <EmbeddedResource Include="Resources\fr-FR.yml" />
    <EmbeddedResource Include="Resources\id-ID.yml" />
    <EmbeddedResource Include="Resources\it-IT.yml" />
    <EmbeddedResource Include="Resources\ru-RU.yml" />
    <EmbeddedResource Include="Resources\sv-SE.yml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AKSoftware.Localization.MultiLanguages.Blazor" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="5.0.11" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="5.0.11" />
  </ItemGroup>

  <Target Name="Translate" AfterTargets="Build" Condition="'$(Configuration)' == 'Debug'">
    <Exec IgnoreExitCode="true" Command="dotnet tool install --global ResourceTranslator.CLI" />
    <Exec Command="resourceTranslator --optionsfile $(ProjectDir)resourceTranslationOptions.json -f $(ProjectDir)Resources\en-US.yml" />
  </Target>

</Project>
