<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Shared.props" />
  <PropertyGroup>
    <RootNamespace>Coworkee.Shared</RootNamespace>
    <AssemblyName>Coworkee.Shared</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\*.yml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AKSoftware.Localization.MultiLanguages.Blazor" Version="1.5.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime.Azure" Version="3.3.19" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Coworkee.Core\Coworkee.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Emails\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

</Project>
