using Coworkee.Domain;
using Coworkee.Infrastructure.Persistence;
using MyApp.Contracts.Catalog;
using Nextended.Core.Attributes;

namespace MyApp.Catalog.Domain;

[Realtime(CatalogPermissions.Brands.View)]
[AutoGenerateDto(Namespace = "MyApp.Contracts.Catalog")]
public sealed class Brand : AuditedEntity, IMultiTenant
{
    public required string Name { get; set; }

    public string? Description { get; set; }

    public decimal Tax { get; set; }

    public Guid TenantId { get; set; }
}
