<Project Sdk="Microsoft.NET.Sdk">  
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />
  <Import Project="..\..\Shared.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>54b92071-131f-43ec-97df-bad034da700f</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\Application\Configurations\ServerConfiguration.cs" Link="Shared\ServerConfiguration.cs" />
    <Compile Include="..\..\Infrastructure\KeycloakSeeder.cs" Link="Shared\KeycloakSeeder.cs" />
    <Compile Include="..\..\Shared\Constants\Application\ApplicationConstants.cs" Link="Shared\ApplicationConstants.cs" />
    <Compile Include="..\..\Shared\Constants\Permission\Permissions.cs" Link="Shared\Permissions.cs" />
    <Compile Include="..\..\Shared\Constants\Permission\RequiresPermissionsAttribute.cs" Link="Shared\RequiresPermissionsAttribute.cs" />
    <Compile Include="..\..\Shared\Constants\Role\RoleConstants.cs" Link="Shared\RoleConstants.cs" />
    <Compile Include="..\..\Shared\Models\CreateUser.cs" Link="Shared\CreateUser.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Nextended.Aspire" Version="9.0.12" />
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.1.0" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" Version="9.1.0" />
    <PackageReference Include="Aspire.Hosting.Azure.SignalR" Version="9.1.0" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="9.1.0" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.1.0" />
    <PackageReference Include="Aspire.Hosting.Keycloak" Version="9.1.0-preview.1.25121.10" />
    <!--<PackageReference Include="Aspire.Hosting.Keycloak" Version="9.0.0-preview.5.24551.3" />-->
    <PackageReference Include="Aspire.Azure.Messaging.ServiceBus" Version="9.1.0" />
    <PackageReference Include="Aspire.Microsoft.Azure.Cosmos" Version="9.1.0" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Ollama" Version="9.3.1-beta.252" />
    <PackageReference Include="Aspire4Wasm" Version="3.0.0" />
    <PackageReference Include="System.IO.Hashing" Version="$(MicrosoftPackagesVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Client\Client.csproj" />
    <ProjectReference Include="..\..\Server\Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Shared\" />
  </ItemGroup>

</Project>
