<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Shared.props" />
  <PropertyGroup>
    <RootNamespace>Coworkee.Application</RootNamespace>
    <AssemblyName>Coworkee.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\lib\Coworkee.Application\Coworkee.Application.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
</Project>