<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Coworkee.Application</RootNamespace>
    <AssemblyName>Coworkee.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="LazyCache" Version="2.4.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.4.9" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.1.0" /> <!--TODO: Remove-->
    <PackageReference Include="Nextended.Core" Version="8.0.16" />
    <PackageReference Include="StringToExpression" Version="2.2.0" />
    <PackageReference Include="Hashids.net" Version="1.7.0" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="GptInvoke" Version="1.2.24121212" />
    <PackageReference Include="OllamaSharp" Version="4.0.11" />

  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Contracts\Services\ExportImport\" />
    <Folder Include="Features\Base\Commands\" />
    <Folder Include="Features\Base\Contracts\" />
    <Folder Include="Features\Notifications\Commands\MarkAll\" />
    <Folder Include="Features\Notifications\Queries\GetAllPaged\" />
    <Folder Include="AssistantFeatures\" />
  </ItemGroup>
</Project>