<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>CleanArchitectureBase.Application</RootNamespace>
    <AssemblyName>CleanArchitectureBase.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="10.3.4" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="10.3.4" />
    <PackageReference Include="LazyCache" Version="2.4.0" />
    <PackageReference Include="MediatR" Version="9.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.2.14" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.1.0" />
    <PackageReference Include="Nextended.Core" Version="5.0.4" />
    
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Contracts\Attributes\" />
    <Folder Include="Contracts\Services\ExportImport\" />
    <Folder Include="Features\Base\Commands\" />
  </ItemGroup>

</Project>
