<Project>
  <PropertyGroup>
    <HostClientInServer>true</HostClientInServer>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <!-- TODO: disable nullable for now because it breaks db operations but we want to enable it  -->
    <MicrosoftPackagesVersion>9.0.3</MicrosoftPackagesVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(HostClientInServer)' == 'true'">
    <DefineConstants>HostClient</DefineConstants>
  </PropertyGroup>
</Project>
