<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    <RootNamespace>CleanArchitectureBase.Client</RootNamespace>
    <AssemblyName>CleanArchitectureBase.Client</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="compilerconfig.json" />
    <Content Remove="Shared\Components\ApplicationLogo.razor" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BuildWebCompiler" Version="1.12.394" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="5.0.10" />
    <PackageReference Include="Blazored.FluentValidation" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="5.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="5.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.7" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="5.0.1" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="5.0.7" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="5.0.7" />
    <PackageReference Include="System.Net.Http.Json" Version="5.0.0" />
    <PackageReference Include="MudBlazor" Version="5.0.14" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.1.2" />
  </ItemGroup>

  <ItemGroup>
    <None Include="compilerconfig.json" />
    <None Include="Shared\Components\ApplicationLogo.razor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Client.Infrastructure\Client.Infrastructure.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MudBlazor.Extensions">
      <HintPath>..\..\..\MudBlazor.Extensions\MudBlazor.Extensions\bin\Debug\net5.0\MudBlazor.Extensions.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
