<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <Import Project="..\..\Shared.props" />
  <PropertyGroup>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    <BlazorWebAssemblyEnableDebugging>true</BlazorWebAssemblyEnableDebugging>
    <!--Experimental-->
    <CompressionEnabled>true</CompressionEnabled>
    <!--<BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
      <BlazorWebAssemblyPreserveCollationData>false</BlazorWebAssemblyPreserveCollationData>
      <PublishTrimmed>true</PublishTrimmed>
      <BlazorEnableCompression>true</BlazorEnableCompression>    
      <TrimMode>link</TrimMode>-->

    <!--End Experimental-->
    <RootNamespace>Coworkee.Client</RootNamespace>
    <AssemblyName>Coworkee.Client</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <RunAOTCompilation>False</RunAOTCompilation>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <RunAOTCompilation>False</RunAOTCompilation>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Blazored.FluentValidation" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="$(MicrosoftPackagesVersion)" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="9.2.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.8.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>    
    <PackageReference Include="System.Net.Http.Json" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="MudBlazor" Version="8.5.1" />
    <PackageReference Include="BlazorJS" Version="2.2.0" />
    <PackageReference Include="MudBlazor.Extensions" Version="8.5.0" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="System.Text.Json" Version="$(MicrosoftPackagesVersion)" />
    <PackageReference Include="Toolbelt.Blazor.HttpClientInterceptor" Version="10.2.0" />
    <!-- gRPC -->
    <PackageReference Include="Google.Protobuf" Version="3.30.2" />
    <PackageReference Include="Grpc.Net.Client" Version="2.70.0" />
    <PackageReference Include="Grpc.Net.Client.Web" Version="2.70.0" />
    <PackageReference Include="Grpc.Tools" Version="2.71.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <Protobuf Include="..\Server\gRPC\Main.proto" GrpcServices="Client" />
  </ItemGroup>
  <ItemGroup>
    <None Include="compilerconfig.json" />
    <None Include="wwwroot\css\open-iconic\font\fonts\open-iconic.svg" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SDK\SDK.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="Pages\Redirect.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="wwwroot\appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Target Name="InjectBackendOrigin" AfterTargets="Publish">
    <Exec Command="sed -i 's|__BACKEND_ORIGIN__|$(BackendOrigin)|g' '$(PublishDir)/wwwroot/appsettings.json'" />
  </Target>

</Project>